name: api_client
description: "Shared HTTP client for calling our backend/stock APIs."
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.0
  flutter: ">=1.17.0"
  dio: ^6.1.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
